import {
  Activity,
  BadgeDollarSign,
  Boxes,
  BriefcaseBusiness,
  Building2,
  HandCoins,
  Home,
  ReceiptText,
  Settings,
  ShieldCheck,
  UserCog,
  Users,
  WalletCards,
} from "lucide-react";

export const drawerNavItems = [
  {
    title: "Dashboard",
    href: "/dashboard",
    icon: Home,
    translationKey: "analytics.moduleName",
  },
  {
    title: "Sales",
    href: "/sales",
    icon: BadgeDollarSign,
    translationKey: "sales.moduleName",
  },
  {
    title: "Purchase",
    href: "/purchase",
    icon: WalletCards,
    translationKey: "purchase.moduleName",
  },
  {
    title: "Inventory",
    href: "/inventory",
    icon: Boxes,
    translationKey: "inventory.moduleName",
  },
  {
    title: "Account",
    href: "/account",
    icon: BriefcaseBusiness,
    translationKey: "accounts.moduleName",
  },
  {
    title: "Warehouse",
    href: "/warehouse",
    icon: Building2,
    translationKey: "warehouse.moduleName",
  },
  {
    title: "Partners",
    href: "/partner",
    icon: Users,
    translationKey: "partners.moduleName",
  },
  {
    title: "Expense",
    href: "/expense",
    icon: ReceiptText,
    translationKey: "expense.moduleName",
  },
  {
    title: "Loan",
    href: "/loan",
    icon: HandCoins,
    translationKey: "loan.moduleName",
  },
  {
    title: "Employee",
    href: "/employee",
    icon: UserCog,
    translationKey: "employee.moduleName",
  },
  {
    title: "Adjustment",
    href: "/adjustment",
    icon: Activity,
    translationKey: "adjustment.moduleName",
  },
  {
    title: "Role & Permissions",
    href: "/role",
    icon: ShieldCheck,
    translationKey: "role.moduleName",
  },
  {
    title: "Audit",
    href: "/audit",
    icon: Activity,
    translationKey: "audit.moduleName",
  },
  {
    title: "Settings",
    href: "/setting",
    icon: Settings,
    translationKey: "setting.moduleName",
  },
];
